"""Generate Xiaohongshu-style SVG card for weekly summary."""
import os
import sys
from pathlib import Path
from typing import Dict

from anthropic import Anthropic

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from autopaper.config import config
from autopaper.utils.web import fetch_url_content


def generate_weekly_summary_card(
    content: str,
    title: str,
    style: str = "tech",
    key_points: list = None,
) -> str:
    """Generate a Xiaohongshu-style SVG card for weekly summary.

    Args:
        content: Weekly issue content or summary
        title: Card title (e.g., "本周技术精选 · 2026-W04")
        style: Card style ("tech" or "news")
        key_points: List of key points to highlight

    Returns:
        SVG code as string
    """
    # Get API key from config (supports both ANTHROPIC_API_KEY and ANTHROPIC_AUTH_TOKEN)
    api_key = config.get_anthropic_api_key()
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY or ANTHROPIC_AUTH_TOKEN environment variable not set")

    # Get optional custom base URL from config (for proxy/custom endpoint)
    base_url = config.get_anthropic_base_url()
    # Get model from config (supports ANTHROPIC_MODEL, ANTHROPIC_DEFAULT_SONNET_MODEL, or default)
    model = config.get_anthropic_model() or config.get_anthropic_sonnet_model() or config.get_model()

    client_kwargs = {"api_key": api_key}
    if base_url:
        client_kwargs["base_url"] = base_url

    client = Anthropic(**client_kwargs)

    # Define color schemes
    if style == "tech":
        primary_color = "#2563eb"  # Blue
        secondary_color = "#3b82f6"
        bg_gradient_start = "#DBEAFE"
        bg_gradient_end = "#EFF6FF"
        card_bg = "#F8FAFC"
        accent_colors = ["#3B82F6", "#60A5FA", "#93C5FD"]
    else:  # news
        primary_color = "#10b981"  # Green
        secondary_color = "#34d399"
        bg_gradient_start = "#D1FAE5"
        bg_gradient_end = "#ECFDF5"
        card_bg = "#F0FDF4"
        accent_colors = ["#10B981", "#34D399", "#6EE7B7"]

    # Prepare key points text
    key_points_text = ""
    if key_points:
        key_points_text = "\n".join([f"• {point}" for point in key_points[:5]])
    else:
        key_points_text = "• 请提供3-5个本周核心要点"

    prompt = f"""你是一个专业的SVG卡片设计师，擅长制作小红书风格的精美信息图。

# 任务
根据以下周刊内容，生成一张适合小红书平台发布的精美SVG卡片代码。

# 输入信息
**标题**: {title}
**风格**: {style}
**核心要点**:
{key_points_text}

**完整内容**:
{content[:2000]}

# 设计要求
1. **尺寸**: 750 x 1334 (竖屏，适合手机阅读)
2. **风格**: 小红书风格 - 高颜值、有设计感、信息清晰
3. **配色方案**:
   - 主色: {primary_color}
   - 辅助色: {secondary_color}
   - 背景渐变: {bg_gradient_start} → {bg_gradient_end}
   - 卡片背景: {card_bg}
   - 强调色: {", ".join(accent_colors)}

4. **视觉元素**:
   - 柔和的渐变背景
   - 几何装饰元素（圆形、波浪等）
   - 圆角矩形卡片
   - 阴影效果增加层次感

5. **内容布局**:
   - 顶部: 标题区（大字号，醒目）
   - 中部: 核心要点列表（3-5条）
   - 底部: 品牌标识 "Generated by AutoPaper"

6. **字体要求**:
   - 标题: 粗体，大字号（36-44px）
   - 正文: 常规，中等字号（24-28px）
   - 使用系统字体栈，确保中文显示

7. **设计原则**:
   - 留白充足，不拥挤
   - 层次分明，重点突出
   - 色彩和谐，视觉舒适
   - 信息清晰，一目了然

# SVG模板结构
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 750 1334" width="750" height="1334">
  <!-- 定义渐变和滤镜 -->
  <defs>
    <linearGradient id="bgGradient" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:{bg_gradient_start};stop-opacity:1" />
      <stop offset="100%" style="stop-color:{bg_gradient_end};stop-opacity:1" />
    </linearGradient>
    <filter id="shadow">
      <feGaussianBlur in="SourceAlpha" stdDeviation="4"/>
      <feOffset dx="0" dy="2" result="offsetblur"/>
      <feComponentTransfer>
        <feFuncA type="linear" slope="0.15"/>
      </feComponentTransfer>
      <feMerge>
        <feMergeNode/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>

  <!-- 主背景 -->
  <rect width="750" height="1334" fill="url(#bgGradient)"/>

  <!-- 装饰元素 -->
  <circle cx="100" cy="100" r="80" fill="{accent_colors[0]}" opacity="0.3"/>
  <circle cx="650" cy="200" r="120" fill="{accent_colors[1]}" opacity="0.2"/>
  <circle cx="150" cy="1200" r="100" fill="{accent_colors[2]}" opacity="0.25"/>

  <!-- 内容卡片区域 -->
  <g>
    <!-- 标题卡片 -->
    <rect x="50" y="80" width="650" height="150" rx="20" fill="white" filter="url(#shadow)"/>
    <text x="375" y="160" font-family="system-ui, sans-serif" font-size="40" font-weight="bold" fill="{primary_color}" text-anchor="middle">{title}</text>

    <!-- 核心要点卡片 -->
    <rect x="50" y="260" width="650" height="900" rx="20" fill="white" filter="url(#shadow)"/>

    <!-- 要点列表 -->
    <g transform="translate(80, 320)">
      <!-- 这里动态生成要点 -->
    </g>

    <!-- 底部品牌 -->
    <text x="375" y="1280" font-family="system-ui, sans-serif" font-size="20" fill="#666" text-anchor="middle">Generated by AutoPaper</text>
  </g>
</svg>
```

# 输出要求
1. 只输出完整的SVG代码（XML格式）
2. 不要有任何额外解释
3. SVG代码必须格式正确，可以直接保存为.svg文件
4. 确保中文字符正确显示（使用UTF-8编码）
5. 根据实际内容要点动态生成列表项

请现在生成SVG代码：
"""

    try:
        response = client.messages.create(
            model=model,
            max_tokens=8192,
            messages=[{"role": "user", "content": prompt}],
        )

        svg_code = response.content[0].text

        # Clean up response if needed
        if "```xml" in svg_code:
            svg_code = svg_code.split("```xml")[1].split("```")[0].strip()
        elif "```svg" in svg_code:
            svg_code = svg_code.split("```svg")[1].split("```")[0].strip()
        elif "```" in svg_code:
            svg_code = svg_code.split("```")[1].split("```")[0].strip()

        return svg_code

    except Exception as e:
        raise RuntimeError(f"Failed to generate SVG card: {e}")


def generate_card_from_url(
    url: str,
    title: str,
    style: str = "tech",
) -> str:
    """Generate SVG card from URL content.

    Args:
        url: URL to fetch content from
        title: Card title
        style: Card style

    Returns:
        SVG code as string
    """
    # Fetch content from URL
    content = fetch_url_content(url)

    # Extract key points from content
    # This is a simple implementation - you can enhance it
    lines = content.split("\n")
    key_points = []

    for line in lines:
        line = line.strip()
        # Look for bullet points or numbered lists
        if line.startswith(("•", "-", "*", "1.", "2.", "3.", "4.", "5.")):
            point = line.lstrip("•-*0123456789.")
            if len(point) > 10 and len(point) < 200:
                key_points.append(point)
            if len(key_points) >= 5:
                break

    return generate_weekly_summary_card(content, title, style, key_points)


def save_svg_card(svg_code: str, output_path: str):
    """Save SVG card to file.

    Args:
        svg_code: SVG code string
        output_path: Path to save SVG file
    """
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(svg_code)


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        print("Usage: python generate_summary_card.py <title> <output_path> [style]")
        print("Example: python generate_summary_card.py '本周技术精选·2026-W04' card.svg tech")
        sys.exit(1)

    title = sys.argv[1]
    output_path = sys.argv[2]
    style = sys.argv[3] if len(sys.argv) > 3 else "tech"

    # Read content from stdin or use sample
    if sys.stdin.isatty():
        # No stdin, use sample content
        content = """
本周的技术焦点集中在 AI 编程范式的演进与传统工程深度的结合上。
我们看到了从简单的代码补全向自主 Agent 和自我参照迭代的跨越。
        """
        key_points = [
            "AI编程工具从对话式向闭环式演进",
            "Ralph Loop引入自我参照迭代机制",
            "传统基础设施精细化治理备受关注",
            "开发者工具链无缝集成趋势明显",
        ]
    else:
        content = sys.stdin.read()
        key_points = []

    try:
        svg = generate_weekly_summary_card(content, title, style, key_points)
        save_svg_card(svg, output_path)
        print(f"✓ SVG card generated: {output_path}")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
